### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ivinator** [AdriBloober/YouTuber_Download#1]
Traceback (most recent call last):
  File "__main__.py", line 59, in <module>
    setup_video()
  File "__main__.py", line 48, in setup_video
    print('Infos: ' + get_infos_about_video(video))
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Ivinator** [comment]
https://www.youtube.com/watch?v=HZy-xSSXQjo

**Comment by AdriBloober** [comment]
I has fixed it :D
